import type { Metadata } from "next";
import "../style/Normalize.css";
import "../style/Root.css";
import "../style/Style.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Next 14 Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
